### ISSUE TITLE
Ruby & liquid should be optional

### ISSUE THREAD

**Issue by pch** [pch/welder#1]
Initially, Ruby dependency was intended just as a convenient way to parse YAML. But if there's a better way to solve it without enforcing Ruby, I'll be happy to consider. Liquid also shouldn't be required if there's no `*.liquid` templates in the project directory.

I'll be happy to accept a PR that makes those dependencies optional.

**Comment by bonndan** [comment]
+1

I can't help you on this one, but I think it is an important issue. Sometimes I've been frustrated with Ansible too and welder looks really interesting!

**Comment by motet-a** [comment]
An awk-based YAML parser could be the solution: https://gist.github.com/epiloque/8cf512c6d64641bde388
