### ISSUE TITLE
[Question] Welder for Deployment

### ISSUE THREAD

**Issue by zimt28** [pch/welder#2]
Hi there!

I'm currently looking for an easy way to deploy an [Elixir](https://github.com/elixir-lang/elixir)/ [Phoenix](https://github.com/phoenixframework/phoenix) application. Was Welder made for setting up servers only or for deployment as well? If so, how would I do it? Just create more playbooks like `deploy`, `start`, `stop`, `migrate` etc?

Thanks!

**Comment by pch** [comment]
Hi!

I have no experience with Elixir/Phoenix apps, but I use welder for setting up the server & the directory structure for my Rails apps. See: https://github.com/pch/welder-contrib/tree/master/modules/rails

For deployment I use [mina](https://github.com/mina-deploy/mina) or [capistrano](http://capistranorb.com).

Welder isn't really meant to be a deployment tool. You could make it work by creating a `deploy` module with a script like the following (pseudocode):

```sh
# modules/deploy/deploy.sh

cd /my/app/path
git clone yourcodebase@gitserver.com release-123
cd release-123

run migrations

cd ..
ln -s /path/to/release-123/ current
restart server
```

But I'm not sure if it's worth the effort. I'd use a dedicated deployment tool instead.
