### ISSUE TITLE
Can't find playbook

### ISSUE THREAD

**Issue by haarts** [pch/welder#9]
When running `welder run <my-playbook>` I get:

```
[FAIL] No /opt/welder/<my-playbook>.yml file found
```

I've installed welder as per instructions. Welder is looking in the installation root for the playbook file. 
The code responsible seems to be located here: https://github.com/pch/welder/blob/master/libexec/welder-run#L12. I believe the `$WELDER_ROOT` variable shouldn't be there.

**Comment by mskuta** [comment]
Recently there was a change in the loading of playbooks (https://github.com/pch/welder/pull/12/commits/654202997df8c1adf174a7128a9e6c0326851d67). Maybe your problem has been solved. Please try again with the latest version.

**Comment by pch** [comment]
Sorry for the long delayed response. I've ran into the same issue and the abovementioned commit seems to be the culprit, so I've decided to revert it to the previous working version. Hope it solves the problem.
